name: Generate and Execute Workflows

on:
  push:
    branches:
      - main

jobs:
  generate-and-execute:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download and Install GitHub CLI
        run: |
          # Download the GitHub CLI binary
          wget https://github.com/cli/cli/releases/download/v2.8.0/gh_2.8.0_linux_amd64.tar.gz

          # Extract the downloaded archive
          tar -xvf gh_2.8.0_linux_amd64.tar.gz

          # Move the extracted binary to a directory in PATH
          sudo mv gh_2.8.0_linux_amd64/bin/gh /usr/local/bin/gh

          # Ensure the binary has executable permissions
          sudo chmod +x /usr/local/bin/gh

          # Verify installation
          gh --version

      - name: Use Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install PyGithub

      - name: Run script to generate dynamic YAML files
        run: python generate_and_execute.py
      
      - name: Check generated YAML files
        run: ls -l dynamic_workflow_*.yml

      - name: Run dynamic workflows
        run: |
          # Loop to execute dynamically generated YAML files
          for file in dynamic_workflow_*.yml; do
            echo "Running $file..."
            gh auth login
            gh workflow run $file
          done
