name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run-dynamic-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Run the generated dynamic workflows sequentially
      - name: Execute Dynamic Workflows
        run: |
          for ((i=1; i<=$COUNT; i++)); do
            echo "Running dynamic_workflow_$i.yml..."
            gh workflow run dynamic_workflow_$i.yml --token $GITHUB_TOKEN
          done
