name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run-dynamic-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      # Run the generated dynamic workflows
      - name: Execute Dynamic Workflows
        run: |
          ls dynamic_workflow_*.yml | while read -r file; do
            echo "Running $file..."
            gh workflow run "$file"
          done
