name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  run-script-and-dynamic-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Grant executable permissions to the script
        run: chmod +x generate_dynamic_yaml.sh

      - name: Execute Bash script
        run: ./generate_dynamic_yaml.sh 5

      - name: Run Dynamic Workflows
        run: |
          for ((i=1; i<=5; i++)); do
            echo "Running dynamic_workflow_$i.yml..."
            gh workflow run dynamic_workflow_$i.yml
          done
